"""init schema

Revision ID: 8caead9c0e13
Revises: 
Create Date: 2026-05-03 22:44:57.335530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caead9c0e13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TipoCategoria',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('Descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Descricao')
    )
    op.create_index(op.f('ix_TipoCategoria_id'), 'TipoCategoria', ['id'], unique=False)
    op.create_table('Categoria',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('IdTipoCategoria', sa.Integer(), nullable=False),
    sa.Column('Descricao', sa.String(length=50), nullable=False),
    sa.Column('Excluido', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['IdTipoCategoria'], ['TipoCategoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Descricao')
    )
    op.create_index(op.f('ix_Categoria_id'), 'Categoria', ['id'], unique=False)
    op.create_table('Despesa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('IdCategoria', sa.Integer(), nullable=False),
    sa.Column('Descricao', sa.String(length=150), nullable=False),
    sa.Column('DiaCobranca', sa.Integer(), nullable=False),
    sa.Column('Valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['IdCategoria'], ['Categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Despesa_id'), 'Despesa', ['id'], unique=False)
    op.create_table('Transacao',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('IdCategoria', sa.Integer(), nullable=True),
    sa.Column('IdDespesa', sa.Integer(), nullable=True),
    sa.Column('Descricao', sa.String(length=150), nullable=False),
    sa.Column('Valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('Data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"IdCategoria" IS NOT NULL OR "IdDespesa" IS NOT NULL', name='ck_at_least_one'),
    sa.CheckConstraint('NOT ("IdCategoria" IS NOT NULL AND "IdDespesa" IS NOT NULL)', name='ck_at_most_one'),
    sa.ForeignKeyConstraint(['IdCategoria'], ['Categoria.id'], ),
    sa.ForeignKeyConstraint(['IdDespesa'], ['Despesa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Transacao_id'), 'Transacao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Transacao_id'), table_name='Transacao')
    op.drop_table('Transacao')
    op.drop_index(op.f('ix_Despesa_id'), table_name='Despesa')
    op.drop_table('Despesa')
    op.drop_index(op.f('ix_Categoria_id'), table_name='Categoria')
    op.drop_table('Categoria')
    op.drop_index(op.f('ix_TipoCategoria_id'), table_name='TipoCategoria')
    op.drop_table('TipoCategoria')
    # ### end Alembic commands ###
