"""adicao campo excluido

Revision ID: a7b06dd63966
Revises: 8caead9c0e13
Create Date: 2026-05-06 11:27:23.233002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b06dd63966'
down_revision: Union[str, Sequence[str], None] = '8caead9c0e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Despesa', sa.Column('Excluido', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('Transacao', sa.Column('Excluido', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transacao', 'Excluido')
    op.drop_column('Despesa', 'Excluido')
    # ### end Alembic commands ###
