"""adicao entidade usuario

Revision ID: abaa26038c0f
Revises: a7b06dd63966
Create Date: 2026-06-09 09:38:53.316458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abaa26038c0f'
down_revision: Union[str, Sequence[str], None] = 'a7b06dd63966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Usuario',
    sa.Column('Id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('Nome', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('PasswordHash', sa.String(length=256), nullable=False),
    sa.Column('PasswordSalt', sa.String(length=64), nullable=False),
    sa.Column('IsAdmin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Usuario_Email'), 'Usuario', ['Email'], unique=True)
    op.create_index(op.f('ix_Usuario_Id'), 'Usuario', ['Id'], unique=False)
    op.add_column('Categoria', sa.Column('IdUsuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Categoria', 'Usuario', ['IdUsuario'], ['Id'])
    op.add_column('Despesa', sa.Column('IdUsuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Despesa', 'Usuario', ['IdUsuario'], ['Id'])
    op.add_column('Transacao', sa.Column('IdUsuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Transacao', 'Usuario', ['IdUsuario'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transacao', type_='foreignkey')
    op.drop_column('Transacao', 'IdUsuario')
    op.drop_constraint(None, 'Despesa', type_='foreignkey')
    op.drop_column('Despesa', 'IdUsuario')
    op.drop_constraint(None, 'Categoria', type_='foreignkey')
    op.drop_column('Categoria', 'IdUsuario')
    op.drop_index(op.f('ix_Usuario_Id'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_Email'), table_name='Usuario')
    op.drop_table('Usuario')
    # ### end Alembic commands ###
