"""remocao password

Revision ID: ccb14ec7d761
Revises: abaa26038c0f
Create Date: 2026-06-09 21:47:53.709276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb14ec7d761'
down_revision: Union[str, Sequence[str], None] = 'abaa26038c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('Excluido', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('Usuario', 'PasswordSalt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Usuario', sa.Column('PasswordSalt', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('Usuario', 'Excluido')
    # ### end Alembic commands ###
