"""idusuario obrigatorio

Revision ID: e5579aaa9ebc
Revises: ccb14ec7d761
Create Date: 2026-06-16 13:47:36.451306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5579aaa9ebc'
down_revision: Union[str, Sequence[str], None] = 'ccb14ec7d761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Categoria', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Despesa', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Transacao', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Transacao', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Despesa', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Categoria', 'IdUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
